# Generated by Django 3.2.20 on 2023-08-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
    ]
